site_name: nachobuilds.io
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - hide-navigation
  palette:
    - scheme: default
      primary: white
      accent: indigo

nav:
  - home:
    - blog/index.md
  - whois: whois.md
  - books: books.md


plugins:
  - blog:
      blog_dir: blog
      post_url_format: "{slug}"
      post_excerpt: optional
      post_readtime: true
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
