[project]
name = "nachobuilds-com"
version = "0.1.0"
description = "website for nachobuilds.com"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.5.49",
    "mkdocs-rss-plugin>=1.17.1",
]
